# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='brand_ambassador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demos', to='core.BrandAmbassador'),
        ),
    ]
